### ISSUE TITLE
open file failed with error

### ISSUE THREAD

**Issue by baoyangc** [baoyangc/dirsha1#2]
my directory structure is bellow
```shell
 tree
.
├── README.md
├── build.sh
├── dirsha1
├── local_libs
│   ├── files.go
│   ├── files_test.go
│   └── testdir
│       ├── test.go1
│       ├── test.md
│       ├── test2.go1
│       ├── test3.go1
│       └── testignore.go1
└── main.go

2 directories, 11 files
```
 
and when I execute the tool,I meet the errors below
```shell
./dirsha1 -dir local_libs -ignore test -result result.txt
panic: open files.go: no such file or directory

goroutine 1 [running]:
panic(0x12c260, 0xc8200164e0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
dirsha1/local_libs.Sha1File(0xc82001422b, 0x8, 0x0, 0x0)
	/Users/baoyangc/code/goprojs/src/dirsha1/local_libs/files.go:44 +0x13b
main.main()
	/Users/baoyangc/code/goprojs/src/dirsha1/main.go:44 +0x4e4
```

it looks like the tool open file with a wrong file path.

**Comment by baoyangc** [comment]
fixed at v1.0.2
